name: hrm.hrm_act_v1@HierarchicalReasoningModel_ACTV1
loss:
  name: losses@ACTLossHead
  loss_type: stablemax_cross_entropy

halt_exploration_prob: 0.1
halt_max_steps: 8  # Reduced for simpler factorization task

H_cycles: 2
L_cycles: 2

H_layers: 2  # Reduced for smaller factorization task
L_layers: 2  # Reduced for smaller factorization task

hidden_size: 256  # Smaller for factorization task
num_heads: 4  # Adjusted for new hidden_size (256 / 64 = 4)
expansion: 4

puzzle_emb_ndim: ${.hidden_size}

pos_encodings: rope
