name: hrm.hrm_act_v1@HierarchicalReasoningModel_ACTV1
loss:
  name: losses@ACTLossHead
  loss_type: stablemax_cross_entropy

halt_exploration_prob: 0.1
halt_max_steps: 16

H_cycles: 2
L_cycles: 2

H_layers: 3  # Reduced from 4 for Apple Silicon
L_layers: 3  # Reduced from 4 for Apple Silicon

hidden_size: 384  # Reduced from 512 for Apple Silicon
num_heads: 6  # Adjusted for new hidden_size (384 / 64 = 6)
expansion: 4

puzzle_emb_ndim: ${.hidden_size}

pos_encodings: rope
