# Factorization training config optimized for Apple Silicon (M4 Pro)

defaults:
  - arch: hrm_factorization_apple_silicon
  - _self_

hydra:
  output_subdir: null

# Data path
data_path: data/factorization-1k

# Hyperparams - Training (optimized for fast learning)
global_batch_size: 64  # Larger batch size for faster training

epochs: 500  # Balanced epochs
eval_interval: 50  # More frequent evaluation
checkpoint_every_eval: True

lr: 5e-4  # Even higher learning rate for faster convergence
lr_min_ratio: 0.1
lr_warmup_steps: 100  # Much shorter warmup for faster start

# Standard hyperparameter settings for LM, as used in Llama
beta1: 0.9
beta2: 0.95
weight_decay: 0.1
puzzle_emb_weight_decay: 0.1

# Hyperparams - Puzzle embeddings training
puzzle_emb_lr: 3e-3  # Higher learning rate for embeddings

# Apple Silicon specific settings
# Disable compilation for better compatibility
# Set via environment variable: DISABLE_COMPILE=true
